# Generated by Django 5.2 on 2025-05-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectShedulingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='matricule',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
