# Generated by Django 5.2 on 2025-05-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectShedulingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membreadmin',
            name='role',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='teacher', max_length=20),
        ),
    ]
