# Generated by Django 5.2 on 2025-05-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectShedulingApp', '0003_alter_student_id_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='student',
            name='matricule',
            field=models.CharField(default='00000', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(default='0000000', max_length=20),
        ),
    ]
