# Generated by Django 5.2 on 2025-05-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectShedulingApp', '0003_alter_teacher_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='niveau',
        ),
    ]
