# Generated by Django 5.2 on 2025-05-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectShedulingApp', '0004_remove_student_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='membreadmin',
            name='email',
            field=models.EmailField(default='aza@gmail.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='membreadmin',
            name='password',
            field=models.CharField(default='nothing', max_length=128),
        ),
    ]
