# Generated by Django 5.2 on 2025-05-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectShedulingApp', '0005_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('building', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('room_number', models.CharField(max_length=10)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_computers', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Salle de classe',
                'verbose_name_plural': 'Salles de classe',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('specs', models.TextField()),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('maintenance', 'En maintenance')], default='available', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Ordinateur',
                'verbose_name_plural': 'Ordinateurs',
            },
        ),
        migrations.CreateModel(
            name='Projector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=20)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('maintenance', 'En maintenance')], default='available', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Vidéo Projecteur',
                'verbose_name_plural': 'Vidéo Projecteurs',
            },
        ),
    ]
