# Generated by Django 5.2 on 2025-05-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectShedulingApp', '0007_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='nothing@gmail.com', max_length=255, unique=True, verbose_name='Adresse email'),
        ),
    ]
