# Generated by Django 5.2 on 2025-05-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectShedulingApp', '0008_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='nothing', max_length=128, verbose_name='password'),
        ),
    ]
