# Generated by Django 5.2 on 2025-05-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectShedulingApp', '0009_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='matricule',
            field=models.CharField(default='00000', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='nothing', max_length=128, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='0000000', max_length=20),
        ),
    ]
