from .StudentViewSet import StudentViewSet,LoginStudentAPIView
from .TeacherViewSet import TeacherViewSet,LoginTeacherAPIView
from .MembreAdminViewSet import MembreAdminViewSet, LoginMembreAdminAPIView
from .OrdinateurViewSet import OrdinateurViewSet
from .VideoProjecteurViewSet import VideoProjecteurViewSet
from .SalleDeClasseViewSet import SalleDeClasseViewSet
from .MembreAdminViewSet import MembreAdminViewSet
from .AdministrativeServiceViewSet import AdministrativeServiceViewSet
from .ReservationViewSet import ReservationViewSet
from .RequeteViewSet import RequeteViewSet
from .DepartmentViewSet import DepartmentViewSet
from .ContextViewSet import ContextViewSet